---
- name: Install Jenkins
  hosts: localhost
  gather_facts: no
  vars:
    jenkins_jdk: java-1.6.0-openjdk
    jenkins_key: gpg-pubkey-d50582e6-4a3feef6
  tasks:
    - name: Ensure java is present
      yum: name={{ jenkins_jdk }} state=present
    - name: Ensure jenkins yum repo is present
      get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo mode=0644
    - name: Check for Jenkins GPG key in rpmdb
      command: rpm -q {{ jenkins_key }}
      register: keycheck
      ignore_errors: true
    - name: Ensure Jenkins GPG key is installed
      command: rpm --import  https://jenkins-ci.org/redhat/jenkins-ci.org.key
      when: keycheck|failed
    - name: Ensure Jenkins is installed
      yum: name=jenkins state=present
    - name: Ensure Jenkins is running
      service: name=jenkins state=running enabled=true
