#!/usr/bin/env ansible-playbook
---
- name: Install node RPMs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install RPMs
      yum: name={{ item }} state=present
      with_items:
        - nodejs
        - npm
