---
- name: Install generic RPMs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install RPMs
      yum: name={{ item }} state=present
      with_items:
        - tmux
        - vim
        - dos2unix
